[build]
  command = "npm install sharp --platform=linux --arch=x64 && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  SKIP_BUILD_STATIC_GENERATION = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200